spring:
  kafka:
    bootstrap-servers: hadoop102:9092,hadoop103:9092,hadoop104:9092
    # 生产者必须 key value 的序列化
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # 消费者必须 key value 的反序列化
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
